apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ConfigMap 
  metadata:
    name: spring-petclinic-vets-service
    namespace: default
  data:
    EUREKA_CLIENT_ENABLED: 'true'
    SPRING_APPLICATION_NAME: spring-petclinic-vets-service
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: spring-petclinic-vets-service
    namespace: default
  spec:
    selector:
      matchLabels:
        app: spring-petclinic-vets-service
    template:
      metadata:
        labels:
          app: spring-petclinic-vets-service
          azure.workload.identity/use: "true"
      spec:
        containers:
        - env:
          - name: APPLICATIONINSIGHTS_ROLE_NAME
            value: spring-petclinic-vets-service
          image: <acr-name>.azurecr.io/spring-petclinic-vets-service:<vets-service-app-image-tag>
          name: spring-petclinic-vets-service
- apiVersion: v1
  kind: Service
  metadata:
    name: spring-petclinic-vets-service
    namespace: default
  spec:
    selector:
      app: spring-petclinic-vets-service
